spring:
  datasource:
    rdiver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  shell:
    interactive:
      enabled: false
  redis:
    port: 6379

logging:
  level:
    root: info

nhn:
  cloud:
    storageUrl: https://api-storage.cloud.toast.com/v1/AUTH_
    containerName: poster
    authUrl: https://api-identity.infrastructure.cloud.toast.com/v2.0


external:
  login:
    url:
      deer: http://tart.nhn.com/remote/login
      giraffe: http://girinticket.nhn.com/auth
      fox: http://airfoxket.nhn.com/api/member/login
      panda: http://moviedapanda.nhn.com/member/login/external
      hippo: http://hippo-playmusical.nhn.com/api/login
      duck: http://movieduck.nhn.com/login
      lion: http://ticget.nhn.com/api/externlogin
      rabbit: http://tomoro.nhn.com/login
      sour: http://playmusical.nhn.com/api/accesslogin
      sweet: http://jogiyo.nhn.com/user/login_all

SKM:
  Url: https://api-keymanager.cloud.toast.com/keymanager/v1.0/appkey/{appkey}/secrets/{keyid}